<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href='shop.css' type='text/css'?>
<!DOCTYPE shop [
<!ENTITY nazwa "Najlepszy sklep">
<!ELEMENT shop (order*,product_list)>
<!ATTLIST shop
  name CDATA #REQUIRED
>
<!ELEMENT order (personal_data,created,status,total,products)>
<!ATTLIST order id ID #REQUIRED>
<!ATTLIST order status (confirmed|unconfirmed) "unconfirmed">
<!ELEMENT personal_data (name,surname,address,contact)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT address (street,city,post_code)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT post_code (#PCDATA)>
<!ELEMENT contact (phone | email)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT created (#PCDATA)>
<!ELEMENT total (#PCDATA)>
<!ATTLIST products  product_id IDREFS #REQUIRED>

<!ELEMENT product_list (product+)>
<!ATTLIST product_list product_id ID #REQUIRED>
<!ELEMENT product (product_name,product_category,price,size,color)>
<!ELEMENT product_name (#PCDATA)>
<!ELEMENT product_category (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT color (#PCDATA)>
]>
<shop name='&nazwa;'>
  <product_list>
    <product product_id='s1'>
      <product_name>S001</product_name>
      <product_category>sukienka</product_category>
      <price>20.50</price>
      <size>38</size>
      <color>biały</color>
    </product>
    <product product_id='s2'>
      <product_name>S002</product_name>
      <product_category>sukienka</product_category>
      <price>30.99</price>
      <size>36</size>
      <color>czarny</color>
    </product>
    <product product_id='s3'>
      <product_name>S003</product_name>
      <product_category>sukienka</product_category>
      <price>45.50</price>
      <size>40</size>
      <color>niebieski</color>
    </product>
    <product product_id='s4'>
      <product_name>S004</product_name>
      <product_category>sukienka</product_category>
      <price>74.89</price>
      <size>40</size>
      <color>żółty</color>
    </product>
    <product product_id='b1'>
      <product_name>B001</product_name>
      <product_category>buty</product_category>
      <price>89.99</price>
      <size>38</size>
      <color>czarny</color>
    </product>
    <product product_id='b2'>
      <product_name>B002</product_name>
      <product_category>buty</product_category>
      <price>79.99</price>
      <size>37</size>
      <color>biały</color> 
    </product>
    <product product_id='b3'>
      <product_name>B003</product_name>
      <product_category>buty</product_category>
      <price>119.89</price>
      <size>37</size>
      <color>czarny</color>
    </product>
    <product product_id='d1'>
      <product_name>D001</product_name>
      <product_category>dodatki</product_category>
      <price>20.99</price>
      <size>uniwersalny</size>
      <color>czarny</color>
    </product>
     <product product_id='d2'>
      <product_name>D002</product_name>
      <product_category>dodatki</product_category>
      <price>18.99</price>
      <size>uniwersalny</size>
      <color>czarny</color>
    </product> 
    <product product_id='k1'>
      <product_name>K001</product_name>
      <product_category>kapelusz</product_category>
      <price>39.99</price>
      <size>uniwersalny</size>
      <color>błętitny</color>
   </product>   
   <product product_id='k2'>
      <product_name>K002</product_name>
      <product_category>kapelusz</product_category>
      <price>39.99</price>
      <size>uniwersalny</size>
      <color>zielony</color>
    </product>    
    <product product_id='k3'>
      <product_name>K003</product_name>
      <product_category>kapelusz</product_category>
      <price>39.99</price>
      <size>uniwersalny</size>
      <color>różowy</color>
    </product>
    <product product_id='t1'>
      <product_name>T001</product_name>
      <product_category>tshirt</product_category>
      <price>19.99</price>
      <size>S</size>
      <color>różowy</color>
    </product>
    <product product_id='t2'>
      <product_name>T001</product_name>
      <product_category>tshirt</product_category>
      <price>19.99</price>
      <size>S</size>
      <color>żółty</color>
    </product>
    <product product_id='t3'>
      <product_name>T002</product_name>
      <product_category>tshirt</product_category>
      <price>9.99</price>
      <size>S</size>
      <color>biały</color>
    </product>
    <product product_id='t4'>
      <product_name>T002</product_name>
      <product_category>tshirt</product_category>
      <price>9.99</price>
      <size>S</size>
      <color>czarny</color>
    </product>
  </product_list>
  <order id='1'>
    <personal_data>
      <name>Maciej</name>
      <surname>Brodecki</surname>
      <address>
        <street>Rydzowa 6</street>
        <city>Łódź</city>
        <post_code>91-211</post_code>
      </address>
      <contact>
        <phone>787373238</phone>
        <email>sda@wp.pl</email>
      </contact>
    </personal_data>
    <created_at>2014-09-26 08:51:04</created_at>
    <total currenct='zł'>72.48</total>
    <products product_id='s1 s2 s3'>
    </products>
  </order>
  <order id='2'>
    <personal_data>
      <name>Adam</name>
      <surname>Świątek</surname>
      <address>
        <street>Radna 6</street>
        <city>Warszawa</city>
        <post_code>54-121</post_code>
      </address>
      <contact>
        <phone>541236985</phone>
        <email>adamiaczek11@interia.pl</email>
      </contact>
    </personal_data>
    <created_at>2014-09-28 14:25:14</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='3' status='confirmed'>
    <personal_data>
      <name>Magda</name>
      <surname>Datek</surname>
      <address>
        <street>Fiorna 32</street>
        <city>Radom</city>
        <post_code>54-852</post_code>
      </address>
      <contact>
        <phone>542415785</phone>
        <email>amadfra@gmail.com</email>
      </contact>
    </personal_data>
    <created_at>2014-09-30 16:45:22</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='4' status='confirmed'>
    <personal_data>
      <name>Elżbieta</name>
      <surname>Toporek</surname>
      <address>
        <street>Strażacka 18</street>
        <city>Warszawa</city>
        <post_code>84-154</post_code>
      </address>
      <contact>
        <phone>874521958</phone>
        <email>koziaserekinteria.pl</email>
      </contact>
    </personal_data>
    <created_at>2014-10-01 09:11:44</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='5' status='confirmed'>
    <personal_data>
      <name>Marcin</name>
      <surname>Majdan</surname>
      <address>
        <street>Elektryczna 41</street>
        <city>Gdańsk</city>
        <post_code>65-147</post_code>
      </address>
      <contact>
        <phone>985147852</phone>
        <email>tiruriru@o2.pl</email>
      </contact>
    </personal_data>
    <created_at>2014-10-01 14:27:54</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='6' status='confirmed'>
    <personal_data>
      <name>Beata</name>
      <surname>Tyczka</surname>
      <address>
        <street>Piwna 5</street>
        <city>Poznań</city>
        <post_code>41-574</post_code>
      </address>
      <contact>
        <phone>915963258</phone>
        <email>gutekpszczolka@gmail.com</email>
      </contact>
    </personal_data>
    <created_at>2014-10-01 14:44:51</created_at>
    <total currenct='zł'></total>
    <products popo=''>
      
    </products>
  </order>
  <order id='7'>
    <personal_data>
      <name>Mateusz</name>
      <surname>Spokojny</surname>
      <address>
        <street>Nerwowa 13</street>
        <city>Szczecin</city>
        <post_code>74-521</post_code>
      </address>
      <contact>
        <phone>874523658</phone>
        <email>prosiaczek1223@wp.pl</email>
      </contact>
    </personal_data>
    <created_at>2014-10-25 10:51:54</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='8'>
    <personal_data>
      <name>Alan</name>
      <surname>Płatek</surname>
      <address>
        <street>Rotundy 16</street>
        <city>Szczebrzeszyn</city>
        <post_code>55-415</post_code>
      </address>
      <contact>
        <phone>841259875</phone>
        <email>chrzaszczyrzewoszyce@wp.pl</email>
      </contact>
    </personal_data>
    <created_at>2014-10-04 07:12:19</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='9'>
    <personal_data>
      <name>Bożydar</name>
      <surname>Aleksis</surname>
      <address>
        <street>Techniczna 66</street>
        <city>Konin</city>
        <post_code>541-748</post_code>
      </address>
      <contact>
        <phone>654852951</phone>
        <email>wpoldobulki@o2.eu</email>
      </contact>
    </personal_data>
    <created_at>2014-10-04 08:24:41</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='10' status='confirmed'>
    <personal_data>
      <name>Agata</name>
      <surname>Bidon</surname>
      <address>
        <street>Bandera 92</street>
        <city>Turek</city>
        <post_code>32-154</post_code>
      </address>
      <contact>
        <phone>951357852</phone>
        <email>jalowaziemia@wp.pl</email>
      </contact>
    </personal_data>
    <created_at>2014-10-04 14:27:40</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='11' status='confirmed'>
    <personal_data>
      <name>Edyta</name>
      <surname>Górska</surname>
      <address>
        <street>Wredna 13a</street>
        <city>Poznań</city>
        <post_code>84-158</post_code>
      </address>
      <contact>
        <phone>985236987</phone>
        <email>toja111222@interia.pl</email>
      </contact>
    </personal_data>
    <created_at>2014-10-04 14:38:54</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='12'>
    <personal_data>
      <name>Amelia</name>
      <surname>Wieloryb</surname>
      <address>
        <street>Potoków 42</street>
        <city>Kraków</city>
        <post_code>84-587</post_code>
      </address>
      <contact>
        <phone>658741259</phone>
        <email>totendziadija@wp.pl</email>
      </contact>
    </personal_data>
    <created_at>2014-10-05 07:42:11</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='13' status='confirmed'>
    <personal_data>
      <name>Marcin</name>
      <surname>Pokuta</surname>
      <address>
        <street>Elen 5</street>
        <city>Warszawa</city>
        <post_code>65-452</post_code>
      </address>
      <contact>
        <phone>753159852</phone>
        <email>atararata@onet.pl</email>
      </contact>
    </personal_data>
    <created_at>2014-10-05 10:10:11</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='14'>
    <personal_data>
      <name>Gustaw</name>
      <surname>Konrad</surname>
      <address>
        <street>Dziadowa 44</street>
        <city>Wilno</city>
        <post_code>00-746</post_code>
      </address>
      <contact>
        <phone>473946294</phone>
        <email>gustaw.konrad@wp.pl</email>
      </contact>
    </personal_data>
    <created_at>2013-12-23 14:07:14</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='15' status='confirmed'>
    <personal_data>
      <name>Adam</name>
      <surname>Mickiewicz</surname>
      <address>
        <street>Pana Tadeusza 17</street>
        <city>Wilno</city>
        <post_code>00-734</post_code>
      </address>
      <contact>
        <phone>829573202</phone>
        <email>a.mickiewicz@gmail.com</email>
      </contact>
    </personal_data>
    <created_at>2013-11-16 16:57:14</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='16' status='confirmed'>
    <personal_data>
      <name>Wisława</name>
      <surname>Szymborska</surname>
      <address>
        <street>Stare Miasto 5</street>
        <city>Kraków</city>
        <post_code>92-612</post_code>
      </address>
      <contact>
        <phone>888213453</phone>
        <email>wisia@onet.eu</email>
      </contact>
    </personal_data>
    <created_at>2013-09-01 23:59:59</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='17'>
    <personal_data>
      <name>Jakub</name>
      <surname>Rząd</surname>
      <address>
        <street>Polesie 3</street>
        <city>Kraków</city>
        <post_code>93-252</post_code>
      </address>
      <contact>
        <phone>666587412</phone>
        <email>parafianieznami@onet.eu</email>
      </contact>
    </personal_data>
    <created_at>2013-04-21 15:29:49</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='18' status='confirmed'>
    <personal_data>
      <name>Artur</name>
      <surname>Więc</surname>
      <address>
        <street>Boruty 42</street>
        <city>Bydgoszcz</city>
        <post_code>65-123</post_code>
      </address>
      <contact>
        <phone>888777444</phone>
        <email>elemeledudki@o2.pl</email>
      </contact>
    </personal_data>
    <created_at>2013-10-12 04:42:23</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='19' status='confirmed'>
    <personal_data>
      <name>Marta</name>
      <surname>Manta</surname>
      <address>
        <street>Baranów Białych 4</street>
        <city>Bytom</city>
        <post_code>92-612</post_code>
      </address>
      <contact>
        <phone>521478523</phone>
        <email>badatrw@renka.pl</email>
      </contact>
    </personal_data>
    <created_at>2013-12-12 21:55:12</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='20'>
    <personal_data>
      <name>Anna</name>
      <surname>Wiadro</surname>
      <address>
        <street>Wesoła 8</street>
        <city>Warszawa</city>
        <post_code>91-532</post_code>
      </address>
      <contact>
        <phone>743431049</phone>
        <email>anna.wiadro@wp.pl</email>
      </contact>
    </personal_data>
    <created_at>2014-02-15 11:20:11</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='21'>
    <personal_data>
      <name>Terencja</name>
      <surname>Szulczewska</surname>
      <address>
        <street>Zgierska 14</street>
        <city>Żyrarów</city>
        <post_code>92-604</post_code>
      </address>
      <contact>
        <phone>43432849</phone>
        <email>t.szulczewska@gmail.com</email>
      </contact>
    </personal_data>
    <created_at>2014-02-13 14:44:44</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>
  <order id='22' status='confirmed'>
    <personal_data>
      <name>Shrek</name>
      <surname>Osioł</surname>
      <address>
        <street>Bagienna Chatka 1</street>
        <city>Bajka</city>
        <post_code>11-111</post_code>
      </address>
      <contact>
        <phone>587456369</phone>
        <email>zielonomi@shrek.com</email>
      </contact>
    </personal_data>
    <created_at>2013-04-12 08:14:28</created_at>
    <total currenct='zł'></total>
    <products>
      
    </products>
  </order>  
</shop>
